fleek-network/lightning

- core/cli/src/commands/opt.rs
- core/syncronizer/src/rpc.rs
While playing with the repo/node I noticed a typo in some error output ("responce"), so this PR updates those references to "response".
> Fix "responce" typo

- core/service-executor/src/service.rs
- lib/sdk/src/api.rs
- lib/sdk/src/ipc_types.rs
We need to query the SGX shared public key from the state in the SGX service, so we have to add this command to the SDK.
> feat: add command to SDK to query the SGX public key

- Cargo.lock
- core/application/src/env.rs
- services/sgx/Cargo.toml
- services/sgx/src/lib.rs
- services/sgx/src/req_res.rs
This adds a check to make sure that the public key corresponding to the enclave's shared secret key matches the public key on the application state. If the keys don't match, the sealed secret key is removed from disk and the runner panics, which will restart the service.
Since we currently don't return the public key from the enclave, we have to query the enclave's HTTP endpoint to get the public key. Once we update the enclave, we can remove that step.
> feat: check enclave public key against public key on state

- core/application/src/state/context.rs
- core/application/src/state/executor/epoch_change.rs
- lib/atomo/src/table.rs
Add `clear` and `as_map` methods to the atomo `TableRef`, and add `clear` to application executor `TableRef`, along with some test coverage. Both are helpers methods that I'm using in the random beacon work. I think these make sense at the atomo / db table level because the operations can be done in a more efficient way by the backend, vs just using the keys iterator, so better to just abstract them away from users of atomo now even if we don't optimize yet.
> feat: add clear and as_map to tableref

- core/application/networks/localnet-example/genesis.toml
- core/application/networks/testnet-stable/genesis.toml
- core/application/src/env.rs
- core/application/src/state/executor.rs
- core/application/src/tests/epoch_change.rs
- core/application/src/tests/utils.rs
- core/test-utils/src/e2e/genesis.rs
- core/types/src/genesis.rs
- core/types/src/state.rs
This PR adds the `EpochsPerYear` protocol parameter, and uses it in place of the `365` constant that's referenced in a few places for that purpose.
The driver for this for me was to make [this test](https://github.com/fleek-network/lightning/blob/main/core/application/src/tests/epoch_change.rs#L429) work with a longer epoch change process (for the committee selection beacon) where iterating through 365 of them for the test isn't practical, but seems like it would be good for it to be a protocol param anyway.
> feat(app): epochs per year protocol param

- Cargo.lock
- core/application/Cargo.toml
- core/application/src/config.rs
- core/utils/src/config.rs
This PR updates the TOML config provider to error when deserialization fails, where previously it would just return the default of the config.
> feat(config): toml deserialization errors

- Cargo.lock
- core/application/networks/localnet-example/genesis.toml
- core/application/networks/testnet-stable/genesis.toml
- core/application/src/config.rs
- core/application/src/env.rs
- core/application/src/tests/utils.rs
- core/e2e/Cargo.toml
- core/e2e/src/bin/spawn_swarm.rs
- core/e2e/src/containerized_node.rs
- core/e2e/src/error.rs
- core/e2e/src/lib.rs
- core/e2e/src/swarm.rs
- core/e2e/tests/checkpoint.rs
- core/e2e/tests/epoch_change.rs
- core/e2e/tests/pinger.rs
- core/e2e/tests/syncronizer.rs
- core/node/src/lib.rs
- core/pinger/src/pinger.rs
- core/rpc/src/lib.rs
- core/test-utils/src/e2e/genesis.rs
- core/types/Cargo.toml
- core/types/src/genesis.rs
- core/types/src/state.rs
- core/utils/src/application.rs
- flake.nix
This PR streamlines the e2e tests using the wait-for-ready and poll-until patterns, making them faster and less flakey. It also adds a protocol param for the reputation ping timeout, previously a 15s constant in the pinger component, and updates `flake.nix` to not exclude e2e tests in CI.
```
PASS [  14.314s] lightning-e2e::syncronizer e2e_syncronize_state
PASS [  16.298s] lightning-e2e::pinger e2e_detect_offline_node
PASS [  18.452s] lightning-e2e::epoch_change e2e_epoch_change_with_some_nodes_not_on_committee
PASS [  18.619s] lightning-e2e::epoch_change e2e_test_staking_auction
PASS [  18.752s] lightning-e2e::checkpoint e2e_checkpoint
PASS [  18.774s] lightning-e2e::epoch_change e2e_epoch_change_all_nodes_on_committee
```
I ran these tests in a loop for a couple hours and didn't hit any …
> test(e2e): streamline the tests

- core/fetcher/src/tests.rs
- core/origin-demuxer/src/tests.rs
- core/origin-http/src/tests.rs
- core/origin-ipfs/src/tests.rs
- core/test-utils/src/server.rs
This PR updates the fetcher and origin tests to use random available listen ports for the origin gateways and pool servers. I noticed that these tests can sometimes fail due to port collisions with other tests.
> chore: use random available ports in fetcher and origin tests

- core/types/src/transaction_client.rs
- core/utils/src/transaction/nonce.rs
- core/utils/src/transaction/runner.rs
- core/utils/src/transaction/tests.rs
This PR updates the transaction client to
- Backfill the nonce before giving up to avoid invalidating in-flight transactions
- Default retry only on `InvalidNonce` revert error
> chore(tx-client): backfill nonce on no more attempts and default retry only on invalid nonce

- lib/sdk/src/header.rs
- lib/sdk/src/http_util.rs
- services/js-poc/src/http/response.rs
- services/js-poc/src/lib.rs
Had an issue returning content other than objects as the body on the functions
This allows users to return `ArrayBuffer` and `Uint8Array` as the body type which are also common as `Response` body types
> feat: Add support for byte array and arraystream bodies on js-poc

- core/application/src/state/executor.rs
- core/application/src/state/executor/epoch_change.rs
- core/application/src/tests/committee_beacon.rs
- core/application/src/tests/epoch_change.rs
- core/application/src/tests/everything_else.rs
- core/application/src/tests/participation.rs
- core/application/src/tests/reputation.rs
- core/application/src/tests/staking.rs
- core/application/src/tests/utils.rs
- core/rpc/src/api/flk.rs
- core/rpc/src/logic/flk_impl.rs
- core/rpc/src/tests.rs
- core/syncronizer/src/rpc.rs
- core/syncronizer/src/syncronizer.rs
- core/types/src/response.rs
- core/utils/src/application.rs
This PR does a few things:
- Update `is_valid_node` to check for `staked + locked >= min_stake` instead of just `staked >= min_stake`, and rename it to `has_sufficient_stake`
- On unstake, set participation to `OptedOut` if the node no longer has sufficient unlocked stake so that participation=False is set on the next epoch change
- On opt-in, check for unlocked stake only (not locked stake)
> chore(app): clean up valid node criteria and node participation on unstake

- core/application/src/env.rs
- core/application/src/state/executor.rs
- core/application/src/state/executor/epoch_change.rs
- core/application/src/tests/staking.rs
- core/types/src/application.rs
- core/types/src/state.rs
Track node registry changes on the `BlockExecutionResponse` by recording it on the `Committee` during execution. For this PR, record `NodeRegistryChange::New` when applying genesis and when creating a new node during `stake`. This is in prep for committee beacon slashing, where `NodeRegistryChange::Slashed` will be added and used.
> feat(app): track node registry changes

- core/pool/src/event.rs
During node shutdown, the pool will sometimes hang and keep the whole thing from shutting down. It doesn't happen often, but when it does it's been tough to track down. It seems to be slightly more reproducable by making a test panic that has a few nodes running with activity between them and looping that until it happens, and so that's what I did and was able to finally track it down using the tokio console, seeing that the pool task was still running, and narrowing it down from there. It's been getting caught up in this loop that attempts to drain the event queue before shutting down:
```rust
while !matches!(self.event_queue.try_recv(), Err(TryRecvError::Empty)) {}
```
But `try_recv` will sometimes return `Err(TryRecvError::Disconnected)` at this point. So this PR updates the loop …
> chore(pool): fix endless loop during shutdown

- core/application/src/tests/staking.rs
- core/archive/src/tests.rs
- core/committee-beacon/tests/tests.rs
- core/dack-aggregator/src/tests.rs
- core/indexer/src/tests.rs
- core/origin-demuxer/src/tests.rs
- core/origin-http/src/tests.rs
- core/origin-ipfs/src/tests.rs
- core/signer/src/tests.rs
- core/test-utils/src/consensus.rs
- core/test-utils/src/e2e/network_builder.rs
- core/types/src/transaction.rs
- core/utils/src/transaction/nonce.rs
- core/utils/src/transaction/runner.rs
- core/utils/src/transaction/tests.rs
When a forwarder error happens during transaction execution, retry with the same nonce if the nonce is still available instead of incrementing. Otherwise the nonce is always incremented and the retry fails/reverts with `InvalidNonce` until other transactions are executed filling in the missing nonces.
> chore(utils/tx): retry with same nonce on forwarder errors

- core/rpc/src/config.rs
- core/types/src/state.rs
Change the rpc port to 4240 to make it consistent with the docs and current testnet
> chore: change rpc port

- core/application/src/state/query.rs
- core/application/src/tests/balances.rs
- core/application/src/tests/utils.rs
- core/interfaces/src/application.rs
- core/rpc/src/api/flk.rs
- core/rpc/src/logic/flk_impl.rs
- core/utils/src/application.rs
This PR adds endpoints to the RPC server that can be used to query the withdraw state tables that were added in #74.
> feat(rpc): add endpoints to query withdraw state table

- core/application/src/state/executor.rs
- core/types/src/transaction.rs
This adds a new transaction type that allows the governance key to bridge in tokens to the network.
This is only temporary until the proof of consensus is implemented for the deposit transaction.
> feat(application): add mint transaction (temporarily)

- core/application/src/state/executor.rs
- core/application/src/state/executor/epoch_change.rs
- core/application/src/state/query.rs
- core/application/src/state/writer.rs
- core/application/src/tests/balances.rs
- core/interfaces/src/application.rs
- core/rpc/src/api/flk.rs
- core/rpc/src/logic/flk_impl.rs
- core/types/src/application.rs
This merges the two withdraw state tables and also introduces types to avoid using tuples.
> chore: simplify withdraw state tables

- core/e2e/src/containerized_node.rs
- core/e2e/src/swarm.rs
- core/e2e/tests/blockstore_server.rs
This add a e2e test for the blockstore server. We spawn a swarm of nodes, put data into node1's blockstore. Then send a request from node2's blockstore server to node1, and make sure that the data matches.
> test(e2e): blockstore server test

- core/broadcast/src/tests.rs
- core/broadcast/tests/broadcast.rs
- core/e2e/src/bin/spawn_swarm.rs
- core/e2e/tests/blockstore_server.rs
- core/e2e/tests/checkpoint.rs
- core/e2e/tests/epoch_change.rs
- core/e2e/tests/pinger.rs
- core/e2e/tests/syncronizer.rs
- core/task-broker/src/tests.rs
- core/test-utils/src/logging.rs
This enables passing a path to the logger so that logs are written to that file. This only concerns e2e tests and some other tests. The logger for the lightning binary is somewhere else.
> chore(test-utils): pass path to logger to log to file

- Cargo.lock
- core/application/src/env.rs
- core/application/src/state/executor.rs
- core/application/src/state/query.rs
- core/application/src/state/writer.rs
- core/e2e/Cargo.toml
- core/e2e/src/containerized_node.rs
- core/e2e/src/swarm.rs
- core/e2e/tests/eth.rs
- core/interfaces/src/application.rs
- core/rpc/src/tests.rs
- core/types/src/application.rs
- core/types/src/response.rs
- core/utils/src/eth.rs
- lib/fleek-crypto/src/keys/mod.rs
- lib/fleek-crypto/src/keys/sk/account.rs
- lib/fleek-crypto/src/keys/sk/client.rs
- lib/fleek-crypto/src/keys/sk/mod.rs
Adds client key management to ethereum account owners.
- Approve and revoke eth contract methods
- state transition functions
- e2e testing for eth (for now just whats added here)
- add client secret key to fleek-crypto
- add client nonce to client table
- left outstanding todo and explaination on client->account map not being set for now (need to decide on pod flow change)
> note: no app state fallback so requires fork on testnet
> app: implement eth abi client key mgmt and layout client nonces

- core/application/src/state/executor.rs
- core/application/src/state/query.rs
- core/application/src/state/writer.rs
- core/application/src/tests/everything_else.rs
- core/e2e/tests/eth.rs
- core/interfaces/src/application.rs
- core/rpc/src/api/flk.rs
- core/rpc/src/logic/flk_impl.rs
- core/types/src/application.rs
- core/types/src/response.rs
- core/types/src/transaction.rs
This adds mints to a state table, adds a method to query the table to the query runner, and also adds an rpc endpoint for it. This is needed for the bridge.
> feat: add mints to state table

- core/application/src/state/executor/epoch_change.rs
We will no longer clear the withdraws table after an epoch change and also don't reset the withdraw id. This way the bridge doesn't have to rely on the archiver. We can garbage collect the withdraws table using the `ClearWithdraws` transaction.
> chore(application): don't clear withdraws after epoch change

- lib/fleek-crypto/src/address.rs
- lib/fleek-crypto/src/transaction.rs
Instead of panicking when the signature is invalid, we want to simply return false.
> chore(fleek-crypto): remove expects from signature verification

- core/consensus/src/epoch_state.rs
Move logs out of waiting loops to avoid spamming.
> chore(consensus): update logs

- core/application/src/state/executor/epoch_change.rs
Instead of resetting the era when the commit phase starts, we have to reset the era, once the epoch change is completed. Otherwise the consensus will be restarted twice in a row. Once for the era reset, and once for the epoch change.
> fix(application): reset era on epoch change
